# Autogenerated by devscripts/update-version.py

__version__ = '2025.11.16.202713'

RELEASE_GIT_HEAD = '8659d31732d59b770a409037cac72658e4c28edc'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'akitty/yt-dlp@master'

ORIGIN = 'akitty/yt-dlp'

_pkg_version = '2025.11.16.202713'
